// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpPonto25.Data;

#nullable disable

namespace SharpPonto25.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SharpPonto25.Entities.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Almoco")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Entrada")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Manha")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Retorno")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Saida")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Tarde")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("TotalDia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
